/*!
 * Copyright 2026, MHP Management und IT-Beratung GmbH and contributors.
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *     http://www.apache.org/licenses/LICENSE-2.0
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

import { TabGroup } from "./section-scan";
import { GROUP_CLASS, PANEL_CLASS, transformGroup } from "./tabs-transform";
import { ensureStyles } from "./styles";

const build = (count: number, memberIndexes: readonly number[]): TabGroup => {
  const section = document.createElement("div");
  section.className = "ui-commons__section__wrapper";

  const columns = Array.from({ length: count }, (_, index) => {
    const column = document.createElement("div");
    column.className = `column-50 ui-commons__section__column`;
    column.dataset.index = String(index);
    const inner = document.createElement("p");
    inner.textContent = `content ${index}`;
    column.appendChild(inner);
    column.appendChild(document.createElement("content-tabs"));
    section.appendChild(column);
    return column;
  });

  document.body.appendChild(section);

  return {
    section,
    members: memberIndexes.map((index) => ({
      column: columns[index],
      widget: columns[index].querySelector<HTMLElement>("content-tabs")!,
    })),
    width: { kind: "percent", percent: 50 },
  };
};

afterEach(() => {
  document.body.innerHTML = "";
});

describe("transformGroup against the host's own stylesheet", () => {
  // What the host really does: a rule generated by styled-components, of the
  // shape `.wrapperClass .columnClass`, injected into the head at runtime —
  // so it is both as specific as any two-class rule we could write and later
  // in the sheet than ours. This is the arrangement a previous attempt lost
  // to, leaving every panel a quarter wide and its content off the page.
  const installHostStyles = (): void => {
    const host = document.createElement("style");
    host.textContent = `
      .ui-commons__section__wrapper .ui-commons__section__column {
        width: 25%;
        max-width: 25%;
        position: relative;
        float: left;
      }
      .${PANEL_CLASS} { width: 25%; }
    `;
    document.head.appendChild(host);
  };

  beforeEach(() => {
    document.head.innerHTML = "";
    ensureStyles();
    installHostStyles();
  });

  it("wins the width for the panel", () => {
    const group = build(3, [0, 1, 2]);

    transformGroup(group);

    expect(getComputedStyle(group.members[0].column).width).toBe("100%");
  });

  it("wins the placement for the panel", () => {
    const group = build(2, [0, 1]);

    transformGroup(group);

    const computed = getComputedStyle(group.members[0].column);
    expect(computed.maxWidth).toBe("100%");
    expect(computed.position).toBe("static");
    expect(computed.float).toBe("none");
  });

  it("leaves a column that is not a panel to the host", () => {
    // The control: without this the first two cases would still pass if the
    // host rule never applied in the first place.
    const group = build(3, [0, 1]);

    transformGroup(group);

    const untouched = group.section.querySelector<HTMLElement>('[data-index="2"]')!;
    expect(getComputedStyle(untouched).width).toBe("25%");
  });
});

describe("transformGroup", () => {
  it("gives a panel the whole width of the group, not its old column share", () => {
    const group = build(3, [0, 1, 2]);

    transformGroup(group);

    group.members.forEach(({ column }) => {
      expect(column.style.getPropertyValue("width")).toBe("100%");
      expect(column.style.getPropertyValue("max-width")).toBe("100%");
    });
  });

  it("states the panel geometry so no host rule can outweigh it", () => {
    // Plain inline already beats an ordinary host rule — the cascade cases
    // above show that. Important is for the host rule that shouts, which jsdom
    // does not resolve faithfully enough to assert on directly, so the
    // decision is pinned here instead.
    const group = build(2, [0, 1]);

    transformGroup(group);

    const { style } = group.members[0].column;
    ["width", "max-width", "flex", "position", "float", "grid-column"].forEach((property) => {
      expect(style.getPropertyPriority(property)).toBe("important");
    });
  });

  it("undoes the host's own column placement", () => {
    const group = build(2, [0, 1]);

    transformGroup(group);

    const { style } = group.members[0].column;
    expect(style.getPropertyValue("position")).toBe("static");
    expect(style.getPropertyValue("float")).toBe("none");
    expect(style.getPropertyValue("grid-column")).toBe("auto");
    expect(style.getPropertyValue("transform")).toBe("none");
  });

  it("states the group width so no host rule can outweigh it", () => {
    const group = build(3, [0, 1]);

    const mounted = transformGroup(group)!;

    expect(mounted.container.style.getPropertyValue("width")).toBe("50%");
    expect(mounted.container.style.getPropertyPriority("width")).toBe("important");
    expect(mounted.container.style.getPropertyPriority("flex")).toBe("important");
  });

  it("hides an inactive panel in a way the host cannot override", () => {
    const group = build(2, [0, 1]);

    transformGroup(group);

    expect(group.members[1].column.style.getPropertyPriority("display")).toBe("important");
    // The active one states nothing, so the column keeps whatever display the
    // host gives it — forcing one here would relayout its content.
    expect(group.members[0].column.style.getPropertyValue("display")).toBe("");
  });

  it("puts the member columns into one container at their old position", () => {
    const group = build(3, [0, 1]);

    const mounted = transformGroup(group)!;

    expect(mounted.container.classList.contains(GROUP_CLASS)).toBe(true);
    expect(group.section.children[0]).toBe(mounted.container);
    expect(group.section.children[1]).toBe(group.section.querySelector('[data-index="2"]'));
    expect(mounted.container.contains(group.members[0].column)).toBe(true);
    expect(mounted.container.contains(group.members[1].column)).toBe(true);
  });

  it("moves the very same column nodes rather than copies", () => {
    const group = build(2, [0, 1]);
    const original = group.members[0].column;
    const child = original.firstElementChild;

    transformGroup(group);

    expect(original.isConnected).toBe(true);
    expect(original.firstElementChild).toBe(child);
  });

  it("shows the first member and hides the rest", () => {
    const group = build(3, [0, 1, 2]);

    transformGroup(group);

    expect(group.members[0].column.hidden).toBe(false);
    expect(group.members[1].column.hidden).toBe(true);
    expect(group.members[2].column.hidden).toBe(true);
  });

  it("switches the active member", () => {
    const group = build(2, [0, 1]);
    const mounted = transformGroup(group)!;

    mounted.setActive(1);

    expect(group.members[0].column.hidden).toBe(true);
    expect(group.members[1].column.hidden).toBe(false);
  });

  it("hides the configuration blocks themselves", () => {
    const group = build(2, [0, 1]);

    transformGroup(group);

    expect(group.members[0].widget.style.display).toBe("none");
  });

  it("claims the added share as a percentage", () => {
    const group = build(2, [0, 1]);

    const mounted = transformGroup(group)!;

    expect(mounted.container.style.width).toBe("50%");
    expect(mounted.container.style.maxWidth).toBe("50%");
  });

  it("asks for the freed space as growth, not as a fixed size", () => {
    // A fixed 50% is wider than the two columns were, whenever the section
    // puts a gap between its columns and sizes them around it. The column
    // beside the group then no longer fits on the line and drops below it.
    const group = build(3, [0, 1]);

    const mounted = transformGroup(group)!;

    expect(mounted.container.style.flex).toBe("50 1 0%");
  });

  it("divides the space in the ratio of the shares when a section holds two groups", () => {
    const two = build(4, [0, 1]);
    const third = two.section.querySelector<HTMLElement>('[data-index="2"]')!;
    const one: TabGroup = {
      section: two.section,
      members: [{ column: third, widget: third.querySelector<HTMLElement>("content-tabs")! }],
      width: { kind: "percent", percent: 25 },
    };

    expect(transformGroup(two)!.container.style.flex).toBe("50 1 0%");
    expect(transformGroup(one)!.container.style.flex).toBe("25 1 0%");
  });

  it("claims a column span when the group asks for one", () => {
    const group = { ...build(3, [0, 1]), width: { kind: "grid", span: 2 } as const };

    const mounted = transformGroup(group)!;

    expect(mounted.container.style.gridColumn).toBe("span 2");
    expect(mounted.container.style.width).toBe("");
  });

  it("claims no width when the group has none", () => {
    const group = { ...build(2, [0, 1]), width: { kind: "none" } as const };

    const mounted = transformGroup(group)!;

    expect(mounted.container.style.width).toBe("");
    expect(mounted.container.style.flex).toBe("");
  });

  it("restores the section exactly on revert", () => {
    const group = build(3, [0, 1]);
    const before = group.section.innerHTML;

    transformGroup(group)!.revert();

    expect(group.section.innerHTML).toBe(before);
  });

  it("refuses to transform a group it already transformed", () => {
    const group = build(2, [0, 1]);
    transformGroup(group);

    expect(transformGroup(group)).toBeNull();
  });

  it("gives the tab bar as the container's first child", () => {
    const group = build(2, [0, 1]);

    const mounted = transformGroup(group)!;

    expect(mounted.container.firstElementChild).toBe(mounted.bar);
    expect(mounted.bar.childElementCount).toBe(0);
  });

  it("setActive with an out-of-range index (>= length) leaves the current panel visible", () => {
    const group = build(2, [0, 1]);
    const mounted = transformGroup(group)!;
    // panel 0 is active after transform
    mounted.setActive(group.members.length); // out of range

    const visibleCount = group.members.filter(({ column }) => !column.hidden).length;
    expect(visibleCount).toBe(1);
    expect(group.members[0].column.hidden).toBe(false);
  });

  it("setActive with a negative index leaves the current panel visible", () => {
    const group = build(2, [0, 1]);
    const mounted = transformGroup(group)!;
    mounted.setActive(1); // activate panel 1 first
    mounted.setActive(-1); // out of range

    const visibleCount = group.members.filter(({ column }) => !column.hidden).length;
    expect(visibleCount).toBe(1);
    expect(group.members[1].column.hidden).toBe(false);
  });

  it("restores the section exactly when members are in the middle of non-member columns", () => {
    // columns 0 and 3 are non-members; 1 and 2 are members
    const group = build(4, [1, 2]);
    const col1 = group.members[0].column;
    const col2 = group.members[1].column;
    const before = group.section.innerHTML;

    transformGroup(group)!.revert();

    expect(group.section.innerHTML).toBe(before);
    // node identity: same objects are back in place
    expect(group.section.children[1]).toBe(col1);
    expect(group.section.children[2]).toBe(col2);
  });

  it("restores a column that was hidden before the transform", () => {
    const group = build(2, [0, 1]);
    group.members[0].column.hidden = true; // pre-existing hidden state

    transformGroup(group)!.revert();

    expect(group.members[0].column.hidden).toBe(true);
  });
});
